In [ ]:
 import pandas as pd  
  import numpy as np

In [7]:
df = pd.read_csv('googleplaystore.csv')  ## loaded the data

In [8]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [9]:
df.drop(['Last Updated','Current Ver','Android Ver'], axis =1, inplace=True) ##preprocess the data ,data we are having numeric value.and some of the column having string type of data

In [10]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity
...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle

In [12]:
df.dropna(inplace =True) ## dropping null values from row inplace return the values in same data frame called df otherwise we have ro assign value in another variabe

In [13]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity
...,...,...,...,...,...,...,...,...,...,...
10834,FR Calculator,FAMILY,4.0,7,2.6M,500+,Free,0,Everyone,Education
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle

# preprocessor numeric data

In [ ]:

## df['Rating'] ##Q.how many appliacation area thera with the rating 4.5c=0
c=0
for value in df['Rating']: ##for value in df['Rating'].values: will print all the values in terms ofnumpy array
    if (value == 4.5):
      c+=1
print(c)

In [41]:
##printing rating in range
c=0
for value in df['Rating'].values:
    if (value < 4.5 and value > 4.0):     ## 4.0-4.5
        c+=1
print(c)

3845

##using function
def inrange(low,uppr):
 c=0
 for value in df['Rating'].values:
    if (value>=low and value<=uppr):     ## 4.0-4.5
        c+=1
 print("number of application with rating between",4.0,'-',uppr,"is",c,".")

In [58]:
inrange(low =4,uppr= 5)

number of application with rating between 4.0 - 5 is 7368 .

##Rating analysis

In [ ]:
#To find average rating of all the application

In [66]:
subm=0
for i in df['Rating'].values:
    subm+=i
print(subm/len(df['Rating'].values))

4.191757420456978

In [65]:
len(df['Rating'].values) ##same you cam repeat for average ratimg

9366

In [71]:
subm=0
for i in df['Reviews'].values:
    subm+=int(i)
print(subm/len(df['Reviews'].values))

514049.8365364083

In [70]:
 df['Reviews'].values ## values are in string means singe inverted comma  we cannot add string with numeric value ..string value should be converted in string

array(['159', '967', '87510', ..., '4', '114', '398307'], dtype=object)

In [72]:
type(int(i))

int

In [79]:
df['Size'].values[0]

'19M'

In [81]:
df['Size'].values[0][:-1] #3removing character value  i.e M

'19'

In [76]:
df['Size'].values

array(['19M', '14M', '8.7M', ..., '3.6M', 'Varies with device', '19M'],
      dtype=object)

In [83]:
df['Size'].unique()  ##to get unique values

array(['19M', '14M', '8.7M', '25M', '2.8M', '5.6M', '29M', '33M', '3.1M',
       '28M', '12M', '20M', '21M', '37M', '2.7M', '5.5M', '17M', '39M',
       '31M', '4.2M', '23M', '6.0M', '6.1M', '4.6M', '9.2M', '5.2M',
       '11M', '24M', 'Varies with device', '9.4M', '15M', '10M', '1.2M',
       '26M', '8.0M', '7.9M', '56M', '57M', '35M', '54M', '201k', '3.6M',
       '5.7M', '8.6M', '2.4M', '27M', '2.5M', '7.0M', '16M', '3.4M',
       '8.9M', '3.9M', '2.9M', '38M', '32M', '5.4M', '18M', '1.1M',
       '2.2M', '4.5M', '9.8M', '52M', '9.0M', '6.7M', '30M', '2.6M',
       '7.1M', '22M', '6.4M', '3.2M', '8.2M', '4.9M', '9.5M', '5.0M',
       '5.9M', '13M', '73M', '6.8M', '3.5M', '4.0M', '2.3M', '2.1M',
       '42M', '9.1M', '55M', '23k', '7.3M', '6.5M', '1.5M', '7.5M', '51M',
       '41M', '48M', '8.5M', '46M', '8.3M', '4.3M', '4.7M', '3.3M', '40M',
       '7.8M', '8.8M', '6.6M', '5.1M', '61M', '66M', '79k', '8.4M',
       '3.7M', '118k', '44M', '695k', '1.6M', '6.2M', '53M', '1.4M',
       '3.0M', '7.2M', '5.8M', '3.8M', '9.6M', '45M', '63M', '49M', '77M',
       '4.4M', '70M', '9.3M', '8.1M', '36M', '6.9M', '7.4M', '84M', '97M',
       '2.0M', '1.9M', '1.8M', '5.3M', '47M', '556k', '526k', '76M',
       '7.6M', '59M', '9.7M', '78M', '72M', '43M', '7.7M', '6.3M', '334k',
       '93M', '65M', '79M', '100M', '58M', '50M', '68M', '64M', '34M',
       '67M', '60M', '94M', '9.9M', '232k', '99M', '624k', '95M', '8.5k',
       '41k', '292k', '11k', '80M', '1.7M', '10.0M', '74M', '62M', '69M',
       '75M', '98M', '85M', '82M', '96M', '87M', '71M', '86M', '91M',
       '81M', '92M', '83M', '88M', '704k', '862k', '899k', '378k', '4.8M',
       '266k', '375k', '1.3M', '975k', '980k', '4.1M', '89M', '696k',
       '544k', '525k', '920k', '779k', '853k', '720k', '713k', '772k',
       '318k', '58k', '241k', '196k', '857k', '51k', '953k', '865k',
       '251k', '930k', '540k', '313k', '746k', '203k', '26k', '314k',
       '239k', '371k', '220k', '730k', '756k', '91k', '293k', '17k',
       '74k', '14k', '317k', '78k', '924k', '818k', '81k', '939k', '169k',
       '45k', '965k', '90M', '545k', '61k', '283k', '655k', '714k', '93k',
       '872k', '121k', '322k', '976k', '206k', '954k', '444k', '717k',
       '210k', '609k', '308k', '306k', '175k', '350k', '383k', '454k',
       '1.0M', '70k', '812k', '442k', '842k', '417k', '412k', '459k',
       '478k', '335k', '782k', '721k', '430k', '429k', '192k', '460k',
       '728k', '496k', '816k', '414k', '506k', '887k', '613k', '778k',
       '683k', '592k', '186k', '840k', '647k', '373k', '437k', '598k',
       '716k', '585k', '982k', '219k', '55k', '323k', '691k', '511k',
       '951k', '963k', '25k', '554k', '351k', '27k', '82k', '208k',
       '551k', '29k', '103k', '116k', '153k', '209k', '499k', '173k',
       '597k', '809k', '122k', '411k', '400k', '801k', '787k', '50k',
       '643k', '986k', '516k', '837k', '780k', '20k', '498k', '600k',
       '656k', '221k', '228k', '176k', '34k', '259k', '164k', '458k',
       '629k', '28k', '288k', '775k', '785k', '636k', '916k', '994k',
       '309k', '485k', '914k', '903k', '608k', '500k', '54k', '562k',
       '847k', '948k', '811k', '270k', '48k', '523k', '784k', '280k',
       '24k', '892k', '154k', '18k', '33k', '860k', '364k', '387k',
       '626k', '161k', '879k', '39k', '170k', '141k', '160k', '144k',
       '143k', '190k', '376k', '193k', '473k', '246k', '73k', '253k',
       '957k', '420k', '72k', '404k', '470k', '226k', '240k', '89k',
       '234k', '257k', '861k', '467k', '676k', '552k', '582k', '619k'],
      dtype=object)

In [84]:
 m=0
 k=0
for size in df['Size'].values:
    if (size!='Varies with device'):
        if(size[-1:]=='M'):
            m+= float(size[:-1])
        if(size[-1:]=='k'):
            k+=float(size[:-1])

In [85]:
size[-1:]

'M'

In [86]:
m  ## total 177328 mb application are there on the playstore according to particular datasets

177328.4999999995

In [87]:
k

110843.5

In [89]:
#to convert k into m 
k/1000 #3 these are the Mb we are having

110.8435

In [91]:
m+k/1000 ##tatal size of all the application so far is 177Gb

177439.3434999995

## data preprocessing -categories

In [94]:
##dealing with string values
unique_category=df["Category"].unique()

In [95]:
unique_category

array(['ART_AND_DESIGN', 'AUTO_AND_VEHICLES', 'BEAUTY',
       'BOOKS_AND_REFERENCE', 'BUSINESS', 'COMICS', 'COMMUNICATION',
       'DATING', 'EDUCATION', 'ENTERTAINMENT', 'EVENTS', 'FINANCE',
       'FOOD_AND_DRINK', 'HEALTH_AND_FITNESS', 'HOUSE_AND_HOME',
       'LIBRARIES_AND_DEMO', 'LIFESTYLE', 'GAME', 'FAMILY', 'MEDICAL',
       'SOCIAL', 'SHOPPING', 'PHOTOGRAPHY', 'SPORTS', 'TRAVEL_AND_LOCAL',
       'TOOLS', 'PERSONALIZATION', 'PRODUCTIVITY', 'PARENTING', 'WEATHER',
       'VIDEO_PLAYERS', 'NEWS_AND_MAGAZINES', 'MAPS_AND_NAVIGATION'],
      dtype=object)

In [96]:
len(unique_category)

33

In [99]:
for i,j in enumerate(unique_category): ##eneumerate function helps us to print index value
    print(i,j)

0 ART_AND_DESIGN
1 AUTO_AND_VEHICLES
2 BEAUTY
3 BOOKS_AND_REFERENCE
4 BUSINESS
5 COMICS
6 COMMUNICATION
7 DATING
8 EDUCATION
9 ENTERTAINMENT
10 EVENTS
11 FINANCE
12 FOOD_AND_DRINK
13 HEALTH_AND_FITNESS
14 HOUSE_AND_HOME
15 LIBRARIES_AND_DEMO
16 LIFESTYLE
17 GAME
18 FAMILY
19 MEDICAL
20 SOCIAL
21 SHOPPING
22 PHOTOGRAPHY
23 SPORTS
24 TRAVEL_AND_LOCAL
25 TOOLS
26 PERSONALIZATION
27 PRODUCTIVITY
28 PARENTING
29 WEATHER
30 VIDEO_PLAYERS
31 NEWS_AND_MAGAZINES
32 MAPS_AND_NAVIGATION

In [102]:
c=0
for i in df['Category'].values:
    if(i=='ART_AND_DESIGN'):
        c+= 1
print(c)  #3for art and design we have 62 application check for remaing one category

62

In [108]:
##using function
def categories(name):
  c=0
  for i in df['Category'].values:
    if(i==name):
        c+= 1
  print(c)

In [111]:
 categories(name='COMICS')

58

# price

In [112]:
##check maximum price
df['Price'].unique()

array(['0', '$4.99', '$3.99', '$6.99', '$7.99', '$5.99', '$2.99', '$3.49',
       '$1.99', '$9.99', '$7.49', '$0.99', '$9.00', '$5.49', '$10.00',
       '$24.99', '$11.99', '$79.99', '$16.99', '$14.99', '$29.99',
       '$12.99', '$2.49', '$10.99', '$1.50', '$19.99', '$15.99', '$33.99',
       '$39.99', '$3.95', '$4.49', '$1.70', '$8.99', '$1.49', '$3.88',
       '$399.99', '$17.99', '$400.00', '$3.02', '$1.76', '$4.84', '$4.77',
       '$1.61', '$2.50', '$1.59', '$6.49', '$1.29', '$299.99', '$379.99',
       '$37.99', '$18.99', '$389.99', '$8.49', '$1.75', '$14.00', '$2.00',
       '$3.08', '$2.59', '$19.40', '$3.90', '$4.59', '$15.46', '$3.04',
       '$13.99', '$4.29', '$3.28', '$4.60', '$1.00', '$2.95', '$2.90',
       '$1.97', '$2.56', '$1.20'], dtype=object)

In [115]:
##to automate the process we need to remove the dollar sign
price =[]
for i in df['Price'].values:
    if('0'==i):
        price.append(0)
    else:
        price.append(float(i[1:])*73.5) ##converting into indian rupee by multiplying73.5

In [116]:
price ##most of the application are free but some application is around 366 rs

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 366.76500000000004,
 366.76500000000004,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 366.76500000000004,
 366.76500000000004,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 293.26500000000004,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 293.26500000000004,
 513.765,
 587.265,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 293.26500000000004,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 293.26500000000004,
 440.26500000000004,
 293.26500000000004,
 293.26500000000004,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 366.76500000000004,
 0,
 0,
 0,
 0,
 0,
 219.76500000000001,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 ...]

# content rating

In [118]:
df['Content Rating'].unique()

array(['Everyone', 'Teen', 'Everyone 10+', 'Mature 17+',
       'Adults only 18+', 'Unrated'], dtype=object)

In [119]:
def content_rating(name):
  c=0
  for i in df['Content Rating'].values:
    if(i==name):
        c+= 1
  print(c)

In [121]:
content_rating('Everyone') ##everyone category we are having 7420 appkication

7420

In [122]:
content_rating('Teen')

1084

In [123]:
content_rating('Everyone 10+')

397

In [124]:
content_rating('Mature 17+')

461

##### next we are going to discuss about how to automate this baove process, here i am written the code six timesjust to get to know about hoe many apps are there in everyone ,teen adult 18+and mature 17+ in this we are having same cateory so, to automate the code so that we do not need to write same code again and again

# AUTOMATIC CATEGORY *IMP

##### so we analyse the category as wellbut we are having a problem ,is that let suppose we are having 40 categories in on e column so i'm not going to write 40 lines of code means i'm not going to repeat the code agin and againfor each and every category,so we should write code which can automatically go throgh each and every category and give me the solution

##### for the above we have only six category so one can go with the the function like we have done above likewise we have made a function inside it we have defined a function and call the function by passing each oone of category that are showing

In [137]:
def content_rating(name):
  c=0
  for i in df['Content Rating'].values:
    if(i==name):
        c+= 1
  print(name,c)

In [138]:
for i in df['Content Rating'].unique():##same can we done with price ,cateory  
    content_rating(i)

Everyone 7420
Teen 1084
Everyone 10+ 397
Mature 17+ 461
Adults only 18+ 3
Unrated 1

In [142]:
##using function
def categories(name):
  c=0
  for i in df['Category'].values:
    if(i==name):
        c+= 1
  print(name,c)

In [143]:
for i in df['Category'].unique():##same can we done with price ,cateory  
    categories(i)

ART_AND_DESIGN 62
AUTO_AND_VEHICLES 73
BEAUTY 42
BOOKS_AND_REFERENCE 178
BUSINESS 303
COMICS 58
COMMUNICATION 328
DATING 195
EDUCATION 155
ENTERTAINMENT 149
EVENTS 45
FINANCE 323
FOOD_AND_DRINK 109
HEALTH_AND_FITNESS 297
HOUSE_AND_HOME 76
LIBRARIES_AND_DEMO 65
LIFESTYLE 314
GAME 1097
FAMILY 1747
MEDICAL 350
SOCIAL 259
SHOPPING 238
PHOTOGRAPHY 317
SPORTS 319
TRAVEL_AND_LOCAL 226
TOOLS 734
PERSONALIZATION 314
PRODUCTIVITY 351
PARENTING 50
WEATHER 75
VIDEO_PLAYERS 160
NEWS_AND_MAGAZINES 233
MAPS_AND_NAVIGATION 124

In [146]:
##printing in variable format
def categories(name):
  c=0
  for i in df['Category'].values:
    if(i==name):
        c+= 1
  print(name,c)
  return c

In [148]:
for i in df['Category'].unique():##same can we done with price ,cateory  
   var = categories(i)
   print(var) #executing this we print none value because this categories function is just  printing something but what we want we want the value should return someting 
              ##so need to return something in above cell  and none value is not printing now

ART_AND_DESIGN 62
62
AUTO_AND_VEHICLES 73
73
BEAUTY 42
42
BOOKS_AND_REFERENCE 178
178
BUSINESS 303
303
COMICS 58
58
COMMUNICATION 328
328
DATING 195
195
EDUCATION 155
155
ENTERTAINMENT 149
149
EVENTS 45
45
FINANCE 323
323
FOOD_AND_DRINK 109
109
HEALTH_AND_FITNESS 297
297
HOUSE_AND_HOME 76
76
LIBRARIES_AND_DEMO 65
65
LIFESTYLE 314
314
GAME 1097
1097
FAMILY 1747
1747
MEDICAL 350
350
SOCIAL 259
259
SHOPPING 238
238
PHOTOGRAPHY 317
317
SPORTS 319
319
TRAVEL_AND_LOCAL 226
226
TOOLS 734
734
PERSONALIZATION 314
314
PRODUCTIVITY 351
351
PARENTING 50
50
WEATHER 75
75
VIDEO_PLAYERS 160
160
NEWS_AND_MAGAZINES 233
233
MAPS_AND_NAVIGATION 124
124

##### i waana pint in datastructur format like in dictionary

In [154]:
dct = {}
for i in df['Category'].unique():
    var = categories(i)
    dct[i] = var

ART_AND_DESIGN 62
AUTO_AND_VEHICLES 73
BEAUTY 42
BOOKS_AND_REFERENCE 178
BUSINESS 303
COMICS 58
COMMUNICATION 328
DATING 195
EDUCATION 155
ENTERTAINMENT 149
EVENTS 45
FINANCE 323
FOOD_AND_DRINK 109
HEALTH_AND_FITNESS 297
HOUSE_AND_HOME 76
LIBRARIES_AND_DEMO 65
LIFESTYLE 314
GAME 1097
FAMILY 1747
MEDICAL 350
SOCIAL 259
SHOPPING 238
PHOTOGRAPHY 317
SPORTS 319
TRAVEL_AND_LOCAL 226
TOOLS 734
PERSONALIZATION 314
PRODUCTIVITY 351
PARENTING 50
WEATHER 75
VIDEO_PLAYERS 160
NEWS_AND_MAGAZINES 233
MAPS_AND_NAVIGATION 124

In [155]:
dct

{'ART_AND_DESIGN': 62,
 'AUTO_AND_VEHICLES': 73,
 'BEAUTY': 42,
 'BOOKS_AND_REFERENCE': 178,
 'BUSINESS': 303,
 'COMICS': 58,
 'COMMUNICATION': 328,
 'DATING': 195,
 'EDUCATION': 155,
 'ENTERTAINMENT': 149,
 'EVENTS': 45,
 'FINANCE': 323,
 'FOOD_AND_DRINK': 109,
 'HEALTH_AND_FITNESS': 297,
 'HOUSE_AND_HOME': 76,
 'LIBRARIES_AND_DEMO': 65,
 'LIFESTYLE': 314,
 'GAME': 1097,
 'FAMILY': 1747,
 'MEDICAL': 350,
 'SOCIAL': 259,
 'SHOPPING': 238,
 'PHOTOGRAPHY': 317,
 'SPORTS': 319,
 'TRAVEL_AND_LOCAL': 226,
 'TOOLS': 734,
 'PERSONALIZATION': 314,
 'PRODUCTIVITY': 351,
 'PARENTING': 50,
 'WEATHER': 75,
 'VIDEO_PLAYERS': 160,
 'NEWS_AND_MAGAZINES': 233,
 'MAPS_AND_NAVIGATION': 124}

# Genres

In [169]:
def genres(name):
  c=0
  for i in df['Genres'].values:
    if(i==name):
        c+= 1

  return c

In [172]:
dct = {}
for i in df['Genres'].unique():
    var = genres(i)
    dct[i] = var

In [173]:
dct

{'Art & Design': 56,
 'Art & Design;Pretend Play': 2,
 'Art & Design;Creativity': 7,
 'Auto & Vehicles': 73,
 'Beauty': 42,
 'Books & Reference': 178,
 'Business': 303,
 'Comics': 57,
 'Comics;Creativity': 1,
 'Communication': 328,
 'Dating': 195,
 'Education;Education': 50,
 'Education': 468,
 'Education;Creativity': 7,
 'Education;Music & Video': 5,
 'Education;Action & Adventure': 6,
 'Education;Pretend Play': 23,
 'Education;Brain Games': 4,
 'Entertainment': 533,
 'Entertainment;Music & Video': 27,
 'Entertainment;Brain Games': 8,
 'Entertainment;Creativity': 3,
 'Events': 45,
 'Finance': 323,
 'Food & Drink': 109,
 'Health & Fitness': 297,
 'House & Home': 76,
 'Libraries & Demo': 65,
 'Lifestyle': 313,
 'Lifestyle;Pretend Play': 1,
 'Adventure;Action & Adventure': 13,
 'Arcade': 207,
 'Casual': 185,
 'Card': 45,
 'Casual;Pretend Play': 31,
 'Action': 358,
 'Strategy': 103,
 'Puzzle': 121,
 'Sports': 333,
 'Music': 21,
 'Word': 28,
 'Racing': 93,
 'Casual;Creativity': 7,
 'Casual;Action & Adventure': 21,
 'Simulation': 194,
 'Adventure': 73,
 'Board': 41,
 'Trivia': 28,
 'Role Playing': 106,
 'Simulation;Education': 3,
 'Action;Action & Adventure': 17,
 'Casual;Brain Games': 13,
 'Simulation;Action & Adventure': 11,
 'Educational;Creativity': 5,
 'Puzzle;Brain Games': 19,
 'Educational;Education': 38,
 'Card;Brain Games': 1,
 'Educational;Brain Games': 6,
 'Educational;Pretend Play': 18,
 'Entertainment;Education': 1,
 'Casual;Education': 3,
 'Music;Music & Video': 3,
 'Racing;Action & Adventure': 20,
 'Arcade;Pretend Play': 1,
 'Role Playing;Action & Adventure': 7,
 'Simulation;Pretend Play': 4,
 'Puzzle;Creativity': 2,
 'Sports;Action & Adventure': 4,
 'Educational;Action & Adventure': 4,
 'Arcade;Action & Adventure': 15,
 'Entertainment;Action & Adventure': 3,
 'Puzzle;Action & Adventure': 5,
 'Strategy;Action & Adventure': 2,
 'Music & Audio;Music & Video': 1,
 'Health & Fitness;Education': 1,
 'Adventure;Education': 2,
 'Board;Brain Games': 15,
 'Board;Action & Adventure': 3,
 'Board;Pretend Play': 1,
 'Casual;Music & Video': 2,
 'Role Playing;Pretend Play': 5,
 'Entertainment;Pretend Play': 2,
 'Video Players & Editors;Creativity': 2,
 'Card;Action & Adventure': 2,
 'Medical': 350,
 'Social': 259,
 'Shopping': 238,
 'Photography': 317,
 'Travel & Local': 225,
 'Travel & Local;Action & Adventure': 1,
 'Tools': 733,
 'Tools;Education': 1,
 'Personalization': 314,
 'Productivity': 351,
 'Parenting': 40,
 'Parenting;Music & Video': 6,
 'Parenting;Brain Games': 1,
 'Parenting;Education': 3,
 'Weather': 75,
 'Video Players & Editors': 158,
 'Video Players & Editors;Music & Video': 3,
 'News & Magazines': 233,
 'Maps & Navigation': 124,
 'Health & Fitness;Action & Adventure': 1,
 'Educational': 32,
 'Casino': 37,
 'Adventure;Brain Games': 1,
 'Lifestyle;Education': 1,
 'Books & Reference;Education': 2,
 'Puzzle;Education': 1,
 'Role Playing;Brain Games': 1,
 'Strategy;Education': 1,
 'Racing;Pretend Play': 1,
 'Communication;Creativity': 1,
 'Strategy;Creativity': 1}